name: Telegram Notification

on:
  workflow_dispatch:
  release:
    types: [published]
    branches:
      - main
      - master

jobs:
  notify:
    name: Send Telegram Message
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            🚀 <b>Nova versão lançada!</b>

            O repositório <b>${{ github.repository }}</b> acaba de publicar a versão <b>${{ github.event.release.tag_name }}</b>.

            📝 <b>Notas do Release:</b>
            ${{ github.event.release.body }}

            🔗 <a href="${{ github.event.release.html_url }}">Ver Release no GitHub</a>